version: "3.7"

services:
  redis:
    image: redis
    hostname: redis-svc
    command: redis-server --requirepass password
    ports:
      - '6379:6379'
    volumes:
      - ./.data/redis:/data
  mongo:
    image: mongo:6.0.4
    hostname: mongo-svc
    ports:
      - '27017:27017'
    volumes:
      - ./.data/mongo:/data/db:rw
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=ccp_db
      - MONGODB_DATA_DIR=/data/db
  ccp:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ccpctr
    image: coredgeio/ccp
    hostname: ccp
    user: app:app
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=password
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_URL=redis://:password@redis:6379
      - LOG_FILE_PATH=/var/log/ccp.log
    ports:
      - '7080:7080'
    volumes:
      - ./clouds.yaml:/etc/ccp/clouds.yaml
      - ./.data/ccp/:/var/log

  ccp-ui:
    container_name: ccp-ui
    image: coredgeio/ccp_ui
    hostname: ccp-ui
    environment:
      - REACT_APP_API_URL=http://ccp:7080
      - REACT_APP_KEYCLOAK_URL=https://192.168.100.109:30600
      - REACT_APP_OIDC_ENABLED=false
      - REACT_APP_OIDC_AUTH_URL=https://192.168.100.109:30600/
      - REACT_APP_OIDC_REALM=cloud2
      - REACT_APP_OIDC_CLIENT_ID=ccp-react
    ports:
      - '3000:80'
